version: '3.4'

services:
  php:
    container_name: symfony_blueprint_app
    build:
      context: ./
      target: deployment
    restart: unless-stopped
    working_dir: /app
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
      - php_socket:/var/run/php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  php_socket:

networks:
  app-network:
    driver: bridge
